### ISSUE TITLE
[feature request] hot-sync

### ISSUE THREAD

**Issue by ngraf** [score-spec/score-k8s#14]
I as a developer
want to have a **hot-sync feature** in `score-k8s` to debug my-changes in a containerized local test environment
to be able to make use of all the advantages of a containerized local developer environment, plus the ability to get fast feedback for my code changes.

*Info*
- In `skaffold` the feature already exists, see documentation https://skaffold.dev/docs/filesync/#inferred-sync-mode
- To convince my team to migrate from `skaffold.yaml` to `score.yaml` this feature is one of the major blockers.

**Comment by astromechza** [comment]
Thanks for cutting the issue @ngraf. We'll do some research into what's practical here.

**Comment by astromechza** [comment]
This ticket may be better suited under https://github.com/score-spec/score-compose as it related to local-machine syncing of a container environment based on file changes.

**Comment by ngraf** [comment]
Well, teams that are used to develop locally in a cluster instead with score-compose will disagree.
I assumed that "score-k8s" targets exactly this audience in first place.

**Comment by astromechza** [comment]
There's some overlap for sure. However score-k8s is not responsible for building or pushing container images for the workloads themselves or even connecting to clusters and deploying things. It relies on external pipelines for this. `score-k8s` _only_ does the transformation step into k8s manifests.

**Comment by ngraf** [comment]
I see. 
Feel free to close this issue then.
