### ISSUE TITLE
[feature request] `completion` subcommand

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-k8s#51]
Let's have a `completion` subcommand for `score-k8s`, like we have with `score-compose`, for consistency:
```
$ score-compose --help
...
Available Commands:
...
  completion    Generate the autocompletion script for the specified shell
...
```

**Comment by Somsubhra** [comment]
Please assign this issue to me - I've added PR here https://github.com/score-spec/score-k8s/pull/60 and doc here https://github.com/score-spec/docs/pull/124 - please review. Thanks!

**Comment by mathieu-benoit** [comment]
Done in https://github.com/score-spec/score-k8s/pull/60.
