### ISSUE TITLE
[bug] `score-k8s init` create the default `score.yaml` in `0600` instead of `0755`

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/score-k8s#57]
`score-k8s init` create the default `score.yaml` in `0600` instead of `0755`:
```
-rw-------  1    169 Oct 16 17:43 score.yaml
```

While `score-compose init` does:
```
-rwxr-xr-x  1    842 Oct 16 17:37 score.yaml
```

We found issues during https://github.com/score-spec/score-k8s/pull/55 in the CI test while running:
```
docker run -v .:/score-k8s --rm score-k8s:test init
cat score.yaml
```
Getting:
```
cat: score.yaml: Permission denied
```

FYI:
- `score-compose init` is doing this: https://github.com/score-spec/score-compose/blob/main/internal/command/init.go#L190
- `score-k8s init` is doing this: https://github.com/score-spec/score-k8s/blob/92c85b8540234f67e3b1052662ef3d171fa48e82/main_init.go#L129C74-L133

For consistency, both should do the same thing: `0755`.

Also, let's update the CI with `cat score.yaml` instead of `ls | grep score.yaml` to check this: https://github.com/score-spec/score-k8s/blob/main/.github/workflows/ci.yaml#L45.

**Comment by Somsubhra** [comment]
Hi - I have raised a PR for this. Please assign this to me and review my changes if they look okay. Thanks!
